name: Bundle and Publish Sources
on: 
  push:
    branches:
      - '**'
      - '!main'

permissions:
  contents: write

jobs:
  build:
    name: Bundle and Publish Sources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: npm test
      - run: npm run typecheck
      - name: Build GitHub Pages artifact
        run: npm run build -- --output dist
      - name: Add custom domain
        run: cp CNAME dist/CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
          clean: true
